### PR TITLE
Do not assume "ordinary text without R code" in output

### PR DESCRIPTION
**Pull request by yihui**
The next version of knitr will no longer print out this message: https://yihui.org/en/2023/01/knitr-progress-bar/

Thanks!

### CODE REVIEW

**Comment by kapsner** [comment]
@yihui Thank you very much!

**Comment by yihui** [comment]
You are welcome! It will be great if you can make a CRAN release at some point so that I won't break your package next time I update **knitr**. Thank you!

**Comment by kapsner** [comment]
I've anticipated this and directly triggered the CRAN release yesterday - the new version is already pubished https://cran.r-project.org/web/packages/autonewsmd/index.html 🎉

**Comment by yihui** [comment]
Wonderful! Thank you so much!

**Pull request merged**
